server:
  port: 8999
spring:
  application:
    name: sh-service-provider
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lbn_project
    username: root
    password: lbn0713
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      #password: lbn0713
  servlet:
    multipart:
      max-file-size: 10MB   # 设置最大上传文件大小为10MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_

dubbo:
  application:
    name: sh-service-provider
    check-serializable: false

  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 250000000
    parameters:
      blockUnilConnectedWait: 250

